// // generated by @ng-toolkit/serverless
// 'use strict';
// const { init } = require("./dist/index");
// const functions = require('firebase-functions');

// const express = require("express");

// const app = express()

// init(app, express.Router());

// exports.expressApp = functions.https.onRequest(app);

// const http = functions.https.onRequest((request, response) => {
//     if (!request.path) {
//     request.url = "/" + request.url;
// }
// return server.app(request, response);
// });

// module.exports = {
//     http
// }


const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();

// Express Servers
const {appServer, simpleServer, corsServer, cleanPathServer} = require('./server');

// HTTP Cloud Functions
const app = functions.https.onRequest(appServer);
// const app = functions.https.onRequest(request, response); => {
//   if (!request.path) {
//     request.url = `/${request.url}`; // Prepend '/' to keep query params if any
//   }

//   return appServer(request, response);
// });
const simple = functions.https.onRequest(simpleServer);
const cors = functions.https.onRequest(corsServer);
const cleanPath = functions.https.onRequest((request, response) => {
  if (!request.path) {
    request.url = `/${request.url}`; // Prepend '/' to keep query params if any
  }

  return cleanPathServer(request, response);
});

module.exports = {
  app,
  cleanPath,
  simple,
  cors,
};